//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoweb_arcos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA
    {
        public int ID_CONTA { get; set; }
        public bool A_PAGAR { get; set; }
        public string CENTRO_CUSTO { get; set; }
        public string CODIGO_BARRA { get; set; }
        public string EMPRESA { get; set; }
        public string BAIXA { get; set; }
        public string OBSERVACOES { get; set; }
        public int NUMERO_NOTAS { get; set; }
        public int ID_PESSOACONT { get; set; }
        public string FORNECEDOR { get; set; }
        public bool CONTABIL { get; set; }
        public string ESPECIE { get; set; }
        public System.DateTime DATA { get; set; }
        public string CAIXA { get; set; }
    
        public virtual PESSOA PESSOA { get; set; }
    }
}
